services:
  homarr:
    image: ghcr.io/homarr-labs/homarr
    container_name: homarr-app
    restart: unless-stopped
    volumes:
      - ${HOMARR_DATA_FOLDER:-./appdata/homarr/config}:/appdata
    environment:
      SECRET_ENCRYPTION_KEY: ${SECRET_ENCRYPTION_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: admin
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis
    ports:
      - ${HOMARR_PORT:-7575}:7575
    networks:
      local:
        ipv4_address: 172.${SUBNET_NUMBER:-20}.0.2

  redis:
    image: redis:7.4.8-alpine
    container_name: homarr-redis
    restart: unless-stopped
    command: >
      redis-server
        --requirepass "${REDIS_PASSWORD}"
        --user admin on +@all ~* >${REDIS_PASSWORD}
    volumes:
      - ${HOMARR_REDIS_FOLDER:-./appdata/homarr/redis}:/data
    networks:
      local:
        ipv4_address: 172.${SUBNET_NUMBER:-20}.0.3

networks:
  local:
    name: homarr-local-network
    ipam:
      config:
        - subnet: 172.${SUBNET_NUMBER:-20}.0.0/16