services:
  homarr:
    image: ghcr.io/homarr-labs/homarr
    container_name: homarr-app
    restart: unless-stopped
    volumes:
      - ./data/homarr/config:/appdata
    environment:
      SECRET_ENCRYPTION_KEY: ${SECRET_ENCRYPTION_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: admin
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis
    ports:
      - 7575:7575
    networks:
      local:

  redis:
    image: redis:7.4.8-alpine
    container_name: homarr-redis
    restart: unless-stopped
    command: >
      redis-server
        --requirepass "${REDIS_PASSWORD}"
        --user admin on +@all ~* >${REDIS_PASSWORD}
    volumes:
      - ./data/homarr/redis:/data
    networks:
      local:

networks:
  local:
    name: homarr-local-network