services:
  homarr:
    image: ghcr.io/homarr-labs/homarr
    container_name: homarr
    hostname: homarr
    restart: unless-stopped
    volumes:
      - ./data:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    network_mode: host