services:
  homarr:
    image: ghcr.io/homarr-labs/homarr
    container_name: homarr-app
    restart: unless-stopped
    volumes:
      - ./data/homarr_data:/appdata
    environment:
      SECRET_ENCRYPTION_KEY: ${SECRET_ENCRYPTION_KEY}
      DB_DRIVER: node-postgres
      DB_DIALECT: postgresql
      DB_URL: "postgresql://admin:${DB_PASSWORD}@db:5432/${DB_NAME}"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: admin
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: admin
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - db
      - redis
    networks:
      local:

  db:
    image: postgres:17.9-alpine
    container_name: homarr-db
    restart: always
    volumes:
      - ./data/homarr_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TIMEZONE:-Etc/UTC}
    networks:
      local:

  redis:
    image: redis:7.4.8-alpine
    container_name: homarr-redis
    restart: unless-stopped
    command: >
      redis-server
        --requirepass "${REDIS_PASSWORD}"
        --user admin on +@all ~* >${REDIS_PASSWORD}
    volumes:
      - ./data/homarr_redis_data:/var/lib/postgresql/data
    networks:
      local:

networks:
  local:
    name: homarr-local-network